# NOTE — Novel / Experimental Model
# ─────────────────────────────────────────────────────────────────────────────
# This is an experimental model architecture evaluated in the v1 ablation study.
# Result: underperforms classical Random Forest at this data scale (~280 training
# samples per LOTO fold). Included to document the negative finding transparently.
# See docs/checkin_2.md §3 and data/processed/model_results_complete.csv.
# ─────────────────────────────────────────────────────────────────────────────

"""
Novel Model Family 1: HyperNEAT-Inspired Topology Search
==========================================================
Implements a CPPN (Compositional Pattern Producing Network)-based approach
where the neural network *weights* are generated by a function of neuron
geometry, rather than learned directly.

The key idea: instead of learning W[i,j] directly, we learn a CPPN f(x_i, y_i, x_j, y_j)
that generates W[i,j] as a function of neuron positions. This allows the model to
discover *geometric patterns* in the matchup feature space — e.g., "features in the
left half of the grid interact with features in the right half" — without us specifying
which pairs of features interact.

Implementation:
  - Lay features on a 1D grid by conceptual proximity (Elo features left, squad right)
  - CPPN: small MLP that maps (x_i, x_j) → weight
  - Evolve CPPN parameters using a genetic algorithm (DEAP)
  - Fitness: LOTO-CV log-loss
"""

import sys
import warnings
import numpy as np
import pandas as pd
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))
warnings.filterwarnings("ignore")

from src.utils.constants import PROCESSED_DIR
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.metrics import log_loss
from sklearn.base import BaseEstimator, ClassifierMixin

try:
    from deap import base, creator, tools, algorithms
    HAS_DEAP = True
except ImportError:
    HAS_DEAP = False

RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)

ELO_FEATURES = [
    "elo_home_pre", "elo_away_pre", "elo_gap", "elo_gap_abs",
    "win_prob_home", "win_prob_away", "k_factor",
    "is_knockout", "is_neutral",
]
ARCHETYPE_LABELS = [
    "heavyweight_clash", "favorite_vs_underdog", "host_pressure",
    "generational_transition", "club_power_mismatch", "tactical_contrast",
    "knockout_volatility",
]


# ─────────────────────────────────────────────────────────────────────────────
#  CPPN: generates connection weights as function of neuron position
# ─────────────────────────────────────────────────────────────────────────────

class CPPN:
    """
    Compositional Pattern Producing Network.
    Maps (x_i, x_j) → weight, where x_i is the position of neuron i
    on the 1D conceptual layout of features.
    Uses a fixed 2-layer MLP; the CPPN *parameters* are evolved by GA.
    """

    def __init__(self, n_in: int, n_hidden: int = 8, n_out_hidden: int = 16):
        self.n_in      = n_in
        self.n_hidden  = n_hidden
        self.n_out_hidden = n_out_hidden
        # Feature positions: lay features evenly on [0, 1]
        self.positions = np.linspace(0, 1, n_in)
        # Parameter count: CPPN has 2 inputs (x_i, x_j) → n_hidden → 1
        # Layer 1: 2*n_hidden + n_hidden (bias) weights
        # Layer 2: n_hidden*1 + 1 (bias) weights
        self.n_params_cppn = 2 * n_hidden + n_hidden + n_hidden + 1

    def generate_weight_matrix(self, cppn_params: np.ndarray) -> np.ndarray:
        """Generate the n_in × n_out weight matrix W using the CPPN."""
        p = cppn_params
        # Unpack CPPN layer 1: (2 → n_hidden)
        nh = self.n_hidden
        W1 = p[:2 * nh].reshape(2, nh)
        b1 = p[2 * nh: 3 * nh]
        W2 = p[3 * nh: 4 * nh].reshape(nh, 1)
        b2 = p[4 * nh: 4 * nh + 1]

        # Generate weight matrix: for each pair (feature i, output j)
        # We generate one output neuron per archetype dimension
        # Here we generate a n_in x n_out_hidden weight matrix
        W = np.zeros((self.n_in, self.n_out_hidden))
        out_positions = np.linspace(0, 1, self.n_out_hidden)

        for i in range(self.n_in):
            for j in range(self.n_out_hidden):
                inp = np.array([self.positions[i], out_positions[j]])
                h = np.tanh(inp @ W1 + b1)
                w_ij = np.tanh(h @ W2 + b2)[0]
                W[i, j] = w_ij
        return W


class HyperNEATClassifier(BaseEstimator, ClassifierMixin):
    """
    HyperNEAT-inspired 3-class classifier.
    Architecture:
      X (n_features) → CPPN-generated W → hidden layer (tanh) → output (softmax)
    The CPPN parameters are optimized by a micro-GA.
    """

    def __init__(self, n_hidden: int = 12, n_generations: int = 30,
                 pop_size: int = 40, random_state: int = 42):
        self.n_hidden    = n_hidden
        self.n_generations = n_generations
        self.pop_size    = pop_size
        self.random_state = random_state
        self.cppn        = None
        self.best_params = None
        self.out_W       = None
        self.out_b       = None
        self.classes_    = np.array([0, 1, 2])

    def _forward(self, X: np.ndarray, cppn_params: np.ndarray) -> np.ndarray:
        """Forward pass using CPPN-generated weights."""
        W_hidden = self.cppn.generate_weight_matrix(cppn_params)
        H = np.tanh(X @ W_hidden)
        # Output layer (fixed random init, fine-tuned separately)
        logits = H @ self.out_W + self.out_b
        # Softmax
        e = np.exp(logits - logits.max(axis=1, keepdims=True))
        return e / e.sum(axis=1, keepdims=True)

    def fit(self, X: np.ndarray, y: np.ndarray):
        rng = np.random.RandomState(self.random_state)
        n_features = X.shape[1]
        self.cppn = CPPN(n_features, n_hidden=8, n_out_hidden=self.n_hidden)
        n_cppn_params = self.cppn.n_params_cppn

        # Fixed output layer (random init, not evolved — keeps GA search space manageable)
        self.out_W = rng.randn(self.n_hidden, 3) * 0.1
        self.out_b = np.zeros(3)

        # Fine-tune output layer given CPPN weights via least-squares approximation
        def fitness(individual):
            params = np.array(individual)
            try:
                probs = self._forward(X, params)
                probs = np.clip(probs, 1e-7, 1 - 1e-7)
                ll = log_loss(y, probs)
            except Exception:
                ll = 10.0
            return (ll,)

        if not HAS_DEAP:
            # Fallback: random search
            best_ll = np.inf
            best_p  = rng.randn(n_cppn_params) * 0.5
            for _ in range(self.pop_size * self.n_generations):
                p = rng.randn(n_cppn_params) * 0.5
                ll = fitness(p)[0]
                if ll < best_ll:
                    best_ll = ll
                    best_p  = p
            self.best_params = best_p
            return self

        # DEAP genetic algorithm
        # Clear any existing DEAP creator registrations
        if hasattr(creator, "FitnessMin"):
            del creator.FitnessMin
        if hasattr(creator, "Individual"):
            del creator.Individual

        creator.create("FitnessMin", base.Fitness, weights=(-1.0,))
        creator.create("Individual", list, fitness=creator.FitnessMin)

        toolbox = base.Toolbox()
        toolbox.register("attr_float", rng.standard_normal)
        toolbox.register("individual", tools.initRepeat,
                         creator.Individual, toolbox.attr_float, n=n_cppn_params)
        toolbox.register("population", tools.initRepeat, list, toolbox.individual)
        toolbox.register("evaluate", fitness)
        toolbox.register("mate",    tools.cxBlend, alpha=0.3)
        toolbox.register("mutate",  tools.mutGaussian, mu=0, sigma=0.3, indpb=0.2)
        toolbox.register("select",  tools.selTournament, tournsize=3)

        pop = toolbox.population(n=self.pop_size)
        algorithms.eaSimple(pop, toolbox,
                            cxpb=0.5, mutpb=0.3,
                            ngen=self.n_generations,
                            verbose=False)

        best_ind = tools.selBest(pop, k=1)[0]
        self.best_params = np.array(best_ind)
        return self

    def predict_proba(self, X: np.ndarray) -> np.ndarray:
        return self._forward(X, self.best_params)

    def predict(self, X: np.ndarray) -> np.ndarray:
        return self.predict_proba(X).argmax(axis=1)
